DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 2
  TEST:
    BATCH_SIZE: 20
  NUM_WORKERS: 2

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "normalize"]

OPTIM:
  NAME: "adam"
  LR: 0.0001
  MAX_EPOCH: 8
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 2
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 10

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  BIOMEDCOOP:
    CTX_INIT: "a photo of a"
    SCCM_LAMBDA: 0.75
    KDSP_LAMBDA: 0.75
    TAU: 1.5
    N_PROMPTS: 50

  ANOMALY_DETECT:
    PREC: "fp32"
    LAMBDA_CONSIST: 0.5
    THRESHOLD_STD: 1.5
    PATCH_TEMPERATURE: 0.07
    MEMORY_BANK_PATH: "memory_bank_mediastinum.pt"
    MASK_MODE: true
    BG_FACTOR: 0.3
    LAMBDA_FUSION: 0.7
    GEN_MODE: true
    GEN_BACKEND: "qwen"
    QWEN_PATH: "models/qwen2.5-0.5b"
    VOCAB_PATH: ""
    CAPTION_JSON: "data/Mediastinum/captions.json"
    TAGS_JSON: "data/Mediastinum/mediastinum_tags.json"
    S_MAX: 8
    N_MAX: 50
    LAMBDA_TAG: 0.5
    LAMBDA_STOP: 0.5
    LAMBDA_WORD: 1.0
    LORA_R: 4
    LORA_ALPHA: 8
    LORA_DROPOUT: 0.1
    VIS_TOKENS: 64
    GEN_MAX_TOKENS: 110
    GEN_TEMPERATURE: 0.4
    PROMPT_LR: 0.0025
    GEN_LR: 0.0001
    STRUCT_CSV: "D:/图神经网络/异常检测/代码demo3/数据集2/胸腺区占位/胸腺区占位_AI3.csv"
    STRUCT_TOKENS: 4
